environment:
  matrix:  
  - job_name: Arcemu VS2010 build
    appveyor_build_worker_image: Visual Studio 2013
    CMAKE_GENERATOR_NAME: Visual Studio 10 2010 Win64
    
  - job_name: Arcemu VS2017 build
    appveyor_build_worker_image: Visual Studio 2017
    CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
    
matrix:
  fast_finish: true

build_script:
- cmd: >-
     mkdir build
     
     cd build
     
     cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=Debug ..\cmake
     
     msbuild Arcemu.sln
     
     copy world\libcrypto*.dll shared\Debug\
     
     copy world\libcurl.dll shared\Debug\
     
     copy world\libssl*.dll shared\Debug\
     
     copy zlib\Debug\zlib.dll shared\Debug\
     
     copy pcre\Debug\pcre.dll world\Debug\
     
     copy zlib\Debug\zlib.dll world\Debug\
     
     ctest -C Debug --verbose
